version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app/Backend
    environment:
      - DATABASE_URL=postgresql://loguser:logpassword@db:5432/logdb
      - PYTHONPATH=/app
      - POSTGRES_DB=logdb
      - POSTGRES_USER=loguser
      - POSTGRES_PASSWORD=logpassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    depends_on:
      db:
        condition: service_healthy
    networks:
      - log_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend_next:
    container_name: frontend_next
    build:
      context: ./Frontendnextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./Frontendnextjs:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      api:
        condition: service_healthy
    networks:
      - log_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=loguser
      - POSTGRES_PASSWORD=logpassword
      - POSTGRES_DB=logdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - log_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loguser -d logdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  rsyslog:
    build:
      context: ./Backend/rsyslog
      dockerfile: Dockerfile
    volumes:
      - rsyslog_logs:/var/log/rsyslog
      - ./Backend/rsyslog/config:/etc/rsyslog.d
      - ./Backend/rsyslog/scripts:/app/rsyslog/scripts
    ports:
      - "514:514/udp"
      - "5014:5014/tcp"
    environment:
      - TZ=UTC
      - RSYSLOG_CONFIG_DIR=/etc/rsyslog.d
      - LOG_LEVEL=DEBUG
    networks:
      - log_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep rsyslogd || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  test-client:
    image: alpine
    command: sh -c 'while true; do logger -n fluent-bit -P 5140 -t TestClient -p local0.info "Test log message from Alpine client"; echo "Sent log message"; sleep 5; done'
    depends_on:
      - fluent-bit
    networks:
      - log_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "logger"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  log_network:
    driver: bridge

volumes:
  postgres_data:
  rsyslog_logs:

